### ISSUE TITLE
image printing

### ISSUE THREAD

**Issue by osamazahabi** [CesarBalzer/Cordova-Plugin-BTPrinter#1]
heyy
when printing using url the method is not giving any output as if it was never called,
and when trying the base64 image printing
, weird shapes are being printed,
how can i fix this?

![img_20190117_131803](https://user-images.githubusercontent.com/20015604/51315375-b6565200-1a5a-11e9-886e-2b15bfed9024.jpg)

**Comment by CesarBalzer** [comment]
See discussion [#issues/71](https://github.com/srehanuddin/Cordova-Plugin-Bluetooth-Printer/issues/71) you probably need to cancel the default printer characters, send the pos commands for this

**Comment by osamazahabi** [comment]
I read about searching in the manual for hex characters, i did find them but now what?
I'm sorry but I'm totally new in working with printers

**Comment by CesarBalzer** [comment]
> I read about searching in the manual for hex characters, i did find them but now what?
> I'm sorry but I'm totally new in working with printers

I think you did not read the whole discussion, there are the snippets of code that were tested with base64, which would be the one here 

[https://pastebin.com/cZ1jXpny](https://pastebin.com/cZ1jXpny)

**Comment by osamazahabi** [comment]
but my case is different because I'm not seeing Chinese and my printer is not the same as his
mine is EXTECH S3750THS

**Comment by CesarBalzer** [comment]
Your case is different but the printer and POS, so you should see in the manual of your printer which are the characters to set the encoding and the type of characters, then mount a javascript with the commands of your printer as I showed in the pastebin link and do the tests.

If you get this code there is the link and run what happens?

**Comment by osamazahabi** [comment]
![screenshot 40](https://user-images.githubusercontent.com/20015604/51319201-18b45000-1a65-11e9-8c20-88d4849ba9c0.png)

**Comment by CesarBalzer** [comment]
Invalid int: "null" 
missing the last parameter, sorry this pastebin was before I changed the plugin, then take this paste and test please
[https://pastebin.com/Tz8jxcp4](https://pastebin.com/Tz8jxcp4)

**Comment by osamazahabi** [comment]
![img_20190117_144232](https://user-images.githubusercontent.com/20015604/51319661-5b2a5c80-1a66-11e9-9098-907a06f45f24.jpg)

**Comment by CesarBalzer** [comment]
sorry, today I'm running at work, I edited the last link in the paste, please test it again, the correct function was missing and you did not even notice it.

> Invalid int: "null"
> missing the last parameter, sorry this pastebin was before I changed the plugin, then take this paste and test please
> https://pastebin.com/24dN2j21

sorry, today I'm running at work, I edited the last link in the paste, please test it again, the correct function was missing and you did not even notice it.

**Comment by osamazahabi** [comment]
i noticed and changed it and the above image is the output of the correct code

**Comment by CesarBalzer** [comment]
so you should change the character encoding, I did this directly in java, now you have to go changing and testing like I did, here in Brazil we use iso 8859 1, if you notice in java this setado this, maybe if you change you help, I even uploaded a commit in the morning altering it, I commented the lines that the encoding was setting.
Sorry if I could not help you anymore

**Comment by osamazahabi** [comment]
okay thank you ill see what can I find

**Comment by mostyn-grp** [comment]
@CesarBalzer, using code from https://pastebin.com/24dN2j21, I get blank feed, I'm using JOLIMARK TP510.
