### ISSUE TITLE
Can it work with POS printers with integrated printer?

### ISSUE THREAD

**Issue by martinlombana** [CesarBalzer/Cordova-Plugin-BTPrinter#10]
Something like this?
I would like to know before I buy one.

Thanks!

![image](https://user-images.githubusercontent.com/18351919/64082576-60949880-cd11-11e9-9012-5685e80c7559.png)

**Comment by CesarBalzer** [comment]
Hello friend, I have not particularly tested on integrated printers, I do not know if its operation is via bluetooth, if so, I suggest you do the listing test and see the result if the name of the printer appears.

**Comment by pedroprez** [comment]
@martinlombana Yes, this plugin works perfect with Sunmi POS V1s and V2 Pro ;)
