### ISSUE TITLE
ESC/POS command not working.

### ISSUE THREAD

**Issue by gemul** [CesarBalzer/Cordova-Plugin-BTPrinter#12]
Hi, thank you for this great library. It works perfectly with an old china-made printer (GPrinter_399B) using printText method.
However, printPOSCommand doesn't seems to work. i've tried printing "0A" (line feed), the console log shows "Data Sent", but the printer does nothing.

**Comment by gemul** [comment]
i've managed to do a line-feed by adding \n (new line) at the end of the string, so it looks like "0A\n".
and the printer does the line-feed. i don't know whether it's the 0A command is working or because the \n character which does the line feed.

**Comment by CesarBalzer** [comment]
The POS commands, must be separated in my understanding, for example to skip 2 lines and give 2 feeds on paper, I use and it works like this:

`BTPrinter.printPOSCommand(null, null, "0A");//Print and feed paper`
`BTPrinter.printPOSCommand(null, null, "0A");//Print and feed paper`
