### ISSUE TITLE
Multiple Bluetooth printer not able to connect

### ISSUE THREAD

**Issue by kalemayur8** [CesarBalzer/Cordova-Plugin-BTPrinter#13]
When I am already connected with one printing device and tries to connect with other printing device it , disconnects from previously connected device. (override the connection with new one).

is there way we can achieve this ?

**Comment by agliottone** [comment]
@kalemayur8  kalemayur8  check my version
https://github.com/agliottone/Cordova-Plugin-BTPrinter2
