### ISSUE TITLE
how to find out is BT Printer still connected ?

### ISSUE THREAD

**Issue by kalemayur8** [CesarBalzer/Cordova-Plugin-BTPrinter#14]
Lets say I am connected with BT printer ABC using BTPrinter.connect(ABC)  , now when I disconnect this BT Printer using BTPrinter.disconnect(ABC), is there any way I can check that this printer is still connected or not , like interval check for connected devices ?, status method does not help as it gives status of all paired devices only

**Comment by CesarBalzer** [comment]
This does not really exist in this plugin, but it is open for developers to implement this functionality.
