### ISSUE TITLE
Problem with listing devices

### ISSUE THREAD

**Issue by gsusalvarado** [CesarBalzer/Cordova-Plugin-BTPrinter#21]
Hello, some Android phones are not showing bluetooth devices

**Comment by CesarBalzer** [comment]
Hello, I'm having problems with some tablets, in the version of android 7, which version of android is having problems?

**Comment by gsusalvarado** [comment]
Hello, in Android 6 or 7 they do not show, I have Android 8 and it works well for me

**Comment by CesarBalzer** [comment]
Yesterday a friend reported that in 10 it is working perfectly too, I still haven't been able to solve the problem in these versions, if you want feel free to make a fork and try some correction

**Comment by gsusalvarado** [comment]
Sounds good to me, if Android 10 works fine

**Comment by stratonlive** [comment]
i tried in android 8, but not showing bluetooth device. Any suggestion?

**Comment by shern91** [comment]
I having the same problem in Android version 9, but it works fine in Android 10.
