### ISSUE TITLE
Have a few questions

### ISSUE THREAD

**Issue by Mate20x** [CesarBalzer/Cordova-Plugin-BTPrinter#27]
@CesarBalzer 

Can use this plugin
But there are some problems

1.How to cut paper?

2.QR code samples are not available

3.If the print is not in English, this symbol will be displayed: (????????)

**Comment by CesarBalzer** [comment]
Hello friend, you need to see in the printer documentation which is the command that makes the paper cut (if the printer has the function), and send it by POS command.
About the QRCode, the example of the other friend was used as described in the readme.
There are character problems that must be solved in the future with the help of the people who use the plugin.
Thanks for the feedback
