### ISSUE TITLE
Second copy of printBase64 produce unreadable print

### ISSUE THREAD

**Issue by rudycox** [CesarBalzer/Cordova-Plugin-BTPrinter#28]
I use your plugin to print printBase64 image (from htm2canvas)
Everything is ok, but when I print the second copy the printer  it produces an unreadable print (seems that are binary data).
The second copy is sent to the printer using the same function.
If I switch OFF and ON the printer after the first print, the second print is ok
I also tried to print some escpos command right after the first print in order to reset everything, but nothing change.

Any idea?

Thank you in advance
~
this is the code:

 BTPrinter.list(function (data) {
  console.log("Success");
  console.log(data); //list of printer in data array
  BTPrinter.connect(function (data) {
    console.log("Success");
    console.log(data)
       BTPrinter.printPOSCommand(null, null, "1B 40");//initialize 1B@
     window.scrollTo(0,0);
     window.ricev_h=$('#ricevuta').height()+50;
    console.log('altezza:'+window.ricev_h);
    window.ricev_w= 365;
	html2canvas(document.getElementById("ricevuta"),{ scrollY: -window.scrollY,width: window.ricev_w, height: window.ricev_h})
            .then((canvas) => {
              var  imageP=canvas.toDataURL().replace(/^data:image\/(png|jpg|jpeg);base64,/, ""); //remove mimetype;
                console.log(imageP);
                BTPrinter.printBase64(function(data){
                    console.log("Success");
                    console.log(data)
				imageP=null;
				   BTPrinter.printPOSCommand(null, null, "0A");
                                   BTPrinter.printPOSCommand(null, null, "0A");
                                   BTPrinter.printPOSCommand(null, null, "0A");
                                    BTPrinter.printPOSCommand(null, null, "0A");
					setTimeout(function(){  //disconnect
						  BTPrinter.disconnect(function(data){
						  console.log("Success");
						  console.log(data)
						  },function(err){
						  console.log("Error");
						  console.log(err)
						  }, "MHT-P8001")
					  }, 1500);
                    },function(err){
                    console.log("Error");
                    console.log(err)
                }, imageP, 0);
            });
            }, function (err) {
            console.log("Error");
            console.log(err)
           }, "MHT-P8001");
     }, function (err) {
       console.log("Error");
      console.log(err);
      });

**Comment by CesarBalzer** [comment]
Try to remove the disconnect from within the function, as I remember I had the same problem

**Comment by rudycox** [comment]
Ok, it works !!
thank you
