### ISSUE TITLE
Print image with method printBase64

### ISSUE THREAD

**Issue by EDcasa** [CesarBalzer/Cordova-Plugin-BTPrinter#4]
What is the correct way to implement the printBase64 method since it prints a series of unknown characters

**Comment by CesarBalzer** [comment]
Test with is [string](https://pastebin.com/TqLPzMeY), for preview image test with [https://codebeautify.org/base64-to-image-converter](https://codebeautify.org/base64-to-image-converter)
```
BTPrinter.printBase64(function(data){
    console.log("Success");
    console.log(data);
},function(err){
    console.log("Error");
    console.log(err);
}, "YOUR STRING",'0');//base64 string, align
```

**Comment by EDcasa** [comment]
The following function should be used to print images:
https://pastebin.com/ea30MGqA
This solution was provided by @CesarBalzer.

**Comment by mostyn-grp** [comment]
@CesarBalzer  @EDcasa 

dont work bro, printer does not respond

**Comment by mohamedazher** [comment]
I use the below code to convert html to image using html2canvas plugin and print base64 image string and it works except that it prints 70% of the page width

```

    html2canvas(document.getElementById("print_url").contentDocument.documentElement).then(canvas => {
        canvas.id = "pos_image_canvas";
        document.body.appendChild(canvas)
        var dataUrl = canvas.toDataURL("image/png");
        console.log(dataUrl);
        BTPrinter.printBase64(function(dataUrl){
            console.log("Success");
            // console.log(data);
        },function(err){
            console.log("Error");
            console.log(err);
        }, dataUrl,'0');
        canvas.remove();
        
        ```
