### ISSUE TITLE
How install this plugin in a project ionic  6.12.0 and Capacitor 2.4.6

### ISSUE THREAD

**Issue by adilson181** [CesarBalzer/Cordova-Plugin-BTPrinter#42]
Hi, how can I do to install this plugin in my ionic 6.12.0 project with capacitor 2.4.6.
I'm trying to run the `cordova plugin add https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter.git` command, but I'm not successful.

I am still studying the ionic framework and took a project to develop. Awaiting return. Thanks!

**Comment by adilson181** [comment]
I managed to solve the problem, I ran the following command: `ionic cordova plugin add git+https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter.git`, Thanks!

**Comment by fdo36** [comment]
how can I use it in a Angular component in Ionic?
