### ISSUE TITLE
printBase64 reduces image size

### ISSUE THREAD

**Issue by jefelon** [CesarBalzer/Cordova-Plugin-BTPrinter#44]
printBase64 reduces the image size and there is no way to send something to make something bigger. The original size is adequate, but this plugin resizes it.

**Comment by aldesha989** [comment]
?

**Comment by mohamedazher** [comment]
The plugin resizes the image before printing. To get the best result, you can the following.

Set the alignment to center while sending the base64 for print.

And you can try opening BluetoothPrinter.java file (not the one in the plugins folder, but the one inside android/src folder) and find the method printBase64, find the resizeImage function which has 3 parameters, first is the image itself, second is the height, third one is the width.

The default is 

```
 bitmap = decodedBitmap;
 int mWidth = bitmap.getWidth();
 int mHeight = bitmap.getHeight();

bitmap = resizeImage(bitmap, 48*8, mHeight);
```

            
You can try changing 48*8 to get the size you want, it still does not print full width, but better than the current size. For me setting size 560 worked the best with center align

**Comment by fatih0057** [comment]
> Eklenti, yazdırmadan önce görüntüyü yeniden boyutlandırır. En iyi sonucu almak için aşağıdakileri yapabilirsiniz.
> 
> Base64'ü yazdırma için gönderirken hizalamayı ortaya ayarlayın.
> 
> Ve BluetoothPrinter.java dosyasını (plugins klasöründeki değil, Android/src klasörünün içindeki dosyayı) açmayı deneyebilir ve printBase64 yöntemini bulabilir, 3 parametreli resizeImage işlevini bulabilirsiniz, ilki görüntünün kendisi, ikincisi yükseklik, üçüncüsü genişliktir.
> 
> Varsayılan
> 
> ```
>  bitmap = decodedBitmap;
>  int mWidth = bitmap.getWidth();
>  int mHeight = bitmap.getHeight();
> 
> bitmap = resizeImage(bitmap, 48*8, mHeight);
> ```
> 
> İstediğiniz boyutu elde etmek için 48*8'i değiştirmeyi deneyebilirsiniz, yine de tam genişlikte yazdırmıyor, ancak mevcut boyuttan daha iyi. Benim için 560 boyutu ayarı, merkez hizalama ile en iyi sonucu verdi

greetings mohamedazher

I want to manually change my current application.
Can you help me.
Best regards


https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter/issues/56#issue-1105083703

**Comment by fatih0057** [comment]
> The plugin resizes the image before printing. To get the best result, you can the following.
> 
> Set the alignment to center while sending the base64 for print.
> 
> And you can try opening BluetoothPrinter.java file (not the one in the plugins folder, but the one inside android/src folder) and find the method printBase64, find the resizeImage function which has 3 parameters, first is the image itself, second is the height, third one is the width.
> 
> The default is
> 
> ```
>  bitmap = decodedBitmap;
>  int mWidth = bitmap.getWidth();
>  int mHeight = bitmap.getHeight();
> 
> bitmap = resizeImage(bitmap, 48*8, mHeight);
> ```
> 
> You can try changing 48*8 to get the size you want, it still does not print full width, but better than the current size. For me setting size 560 worked the best with center align

greetings mohamedazher

I want to manually change my current application.
Can you help me.
Best regards



https://github.com/CesarBalzer/Cordova-Plugin-BTPrinter/issues/56#issue-1105083703
