### ISSUE TITLE
not able to print Euro symbol,it printing ? insted of euro symbol

### ISSUE THREAD

**Issue by pradnya94** [CesarBalzer/Cordova-Plugin-BTPrinter#50]

**Comment by piefabr** [comment]
I have resolved with this code before BTPrinter.printText function

     BTPrinter.setEncoding(function (data) {
      console.log(data)
     }, function (err) {
      console.log("setEncoding", err)
     }, "Cp858")

     BTPrinter.printPOSCommand(function (data) {
      console.log(data)
     }, function (err) {
      console.log(err)
     }, "1B7413");

**Comment by pradnya94** [comment]
I have resolved with this code after BTPrinter.printText function

var strEncoding = "GB18030";
			  BTPrinter.setEncoding(function (data) {
			    showToast(strEncoding);
			    console.log(data);
			  }, function (err) {
			    console.error(err);
			  }, strEncoding);
